wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1678628496.472918
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 13
      - 23
      4: 3.9.12
      5: 0.13.10
      8:
      - 5
    visualize:
      conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
